#!/usr/bin/env python3
"""Generate LaTeX tables (booktabs) from result JSONs:
TABLE_1_benchmark.tex  family x primitive x modality x rows + admission stats
TABLE_2_main.tex       seed-averaged three-architecture comparison
TABLE_3_adapt.tex      adaptation cost per held-out task
TABLE_4_appendix.tex   per-family x primitive, per-seed mean+-std for #1/#2
Also prints cross-checks against the numbers quoted in the draft."""
import numpy as np
from collections import defaultdict
from paper_plot_style import *

man = load(UNI / "manifest.json")
tasks = {k: v for k, v in man.items() if v.get("status") == "ready"}
adm = load(UNI / "admission_report.json")
QGROUPS = qgroups_conflict()  # see helper docstring: on-disk report is post-isolation zeros
sa = load(AE / "seed_avg_three_way.json")
adapt = load(AE / "adapt_cost.json")

PRIMS = ["choice", "noul", "score", "multi_noul"]
MODTAG = {"dna": "D", "protein": "P", "rna": "R"}

def esc(s):
    return s.replace("_", "\\_")

# aggregate per family
fam = defaultdict(lambda: {"prim": defaultdict(int), "rows": dict(train=0, dev=0, test=0),
                           "mods": set(), "n": 0, "q": 0})
mod_counter = defaultdict(int)
for tid, v in tasks.items():
    f = family_of(tid)
    fam[f]["prim"][v["primitive"]] += 1
    fam[f]["n"] += 1
    fam[f]["mods"].update(v["modality"])
    fam[f]["q"] += v.get("quarantined_groups", 0)
    for s in ("train", "dev", "test"):
        fam[f]["rows"][s] += v.get(s, 0)
    ms = v["modality"]
    if len(ms) > 1:            # double-sequence task (pair / homology)
        mod_counter["double"] += 1
    else:
        mod_counter[ms[0]] += 1
fams_sorted = sorted(fam, key=lambda f: -fam[f]["n"])

tot = {"n": sum(fam[f]["n"] for f in fam), "q": sum(fam[f]["q"] for f in fam),
       "train": sum(fam[f]["rows"]["train"] for f in fam),
       "dev": sum(fam[f]["rows"]["dev"] for f in fam),
       "test": sum(fam[f]["rows"]["test"] for f in fam)}
print("CHECK totals:", tot)
print("CHECK primitive counts:", {p: sum(fam[f]["prim"][p] for f in fam) for p in PRIMS})
print("CHECK modality counts:", dict(mod_counter))
print("CHECK leak tasks:", adm["summary"]["tasks_with_train_test_leak"],
      "| cross-task dup seqs:", adm["summary"]["n_cross_task_duplicate_sequences"])

# ---------------- Table 1 ----------------
lines = [r"% Table 1: benchmark composition (generated by gen_tables.py)",
         r"\begin{table}[t]", r"\centering",
         r"\caption{BioDecisionBench composition. Rows are the %d source families (canonical" % len(fams_sorted),
         r"task-id prefix map used by the training scheduler; \texttt{lg\_}/\texttt{protein\_homology} share the",
         r"\texttt{local\_snapshots} family). Task counts are per evaluation unit; ProteinGym's 217 assays",
         r"share one question type. Admission: 0 train/test sequence leaks after isolation;",
         f"{QGROUPS:,}".replace(",", "{,}") + r" conflicting-label groups quarantined (not majority-voted);",
         f"{adm['summary']['n_cross_task_duplicate_sequences']:,}".replace(",", "{,}") +
         r" cross-task duplicate sequences kept isolated per task.}",
         r"\label{tab:benchmark}",
         r"\small",
         r"\begin{tabular}{lrrrrrrrrr}", r"\toprule",
         r"Family & Mod. & choice & noul & score & multi & Tasks & Train & Dev & Test",
         r"\\ \midrule"]
for f in fams_sorted:
    d = fam[f]
    mods = "+".join(MODTAG[m] for m in ("dna", "protein", "rna") if m in d["mods"])
    pr = [d["prim"][p] for p in PRIMS]
    lines.append(esc(f) + f" & {mods} & " + " & ".join(str(x) if x else "--" for x in pr) +
                 f" & {d['n']} & {d['rows']['train']:,} & {d['rows']['dev']:,} & {d['rows']['test']:,} \\\\")
lines.append(r"\midrule")
allp = [sum(fam[f]["prim"][p] for f in fam) for p in PRIMS]
modstr = (f"D{mod_counter['dna']}+P{mod_counter['protein']}+R{mod_counter['rna']}"
          f"+{mod_counter['double']}D")
lines.append(r"\textbf{Total} & " + modstr + " & " + " & ".join(map(str, allp)) +
             f" & {tot['n']} & {tot['train']:,} & {tot['dev']:,} & {tot['test']:,} \\\\" )
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_1_benchmark.tex").write_text("\n".join(lines))

# ---------------- Table 2 ----------------
t2 = [r"% Table 2: main seed-averaged three-way comparison (generated by gen_tables.py)",
      r"\begin{table}[t]", r"\centering",
      r"\caption{Matched-compute three-way comparison, seed-averaged over 3 seeds. "
      r"Mean$\pm$SEM across tasks after per-task seed averaging; run-std is the across-seed "
      r"standard deviation of the task-macro aggregate. \#3 (frozen Qwen3-0.6B candidate "
      r"likelihood) is \emph{not} compute-matched and is reported for reference.}",
      r"\label{tab:main}", r"\footnotesize\setlength{\tabcolsep}{3pt}",
      r"\begin{tabular}{llcccccc}", r"\toprule",
      r"Primitive & Metric & $n$ & \#1 shared & \#2 task heads & \#3 frozen LM & run-std \#1 & run-std \#2 \\",
      r"\midrule"]
MET = {"choice": ("accuracy", "acc"), "noul": ("AUROC", "auroc"), "score": ("Spearman", "spear")}
for g in ("choice", "noul", "score"):
    d = sa[g]
    nm, _ = MET[g]
    g3 = "--" if d["gen3_mean"] is None else f"{d['gen3_mean']:.3f}"
    t2.append(f"{g} & {nm} & {d['n']} & {d['shared_mean']:.3f}$\\pm${d['shared_sem']:.3f} & "
              f"{d['taskhead_mean']:.3f}$\\pm${d['taskhead_sem']:.3f} & {g3} & "
              f"{d['run_std']['shared']:.3f} & {d['run_std']['taskhead']:.3f} \\\\")
w = sa["per_task_wins_seedmean"]
wins_row = (r"Per-task seed-mean wins (\#1 / tie / \#2) & & & \multicolumn{5}{r}{"
            + f"{w['shared']} / {w['tie']} / {w['taskhead']}" + r"} \\")
t2 += [r"\addlinespace", wins_row,
       r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_2_main.tex").write_text("\n".join(t2))

# ---------------- Table 3 ----------------
t3 = [r"% Table 3: adaptation cost (generated by gen_tables.py)",
      r"\begin{table}[t]", r"\centering",
      r"\caption{Adaptation cost on 11 held-out tasks: \#1 zero-shot (no labels, no training) "
      r"vs \#2 new linear head fitted on $N$ labels (frozen shared encoder). "
      r"\#2 catches or beats \#1's zero-shot on 7/11 tasks already at $N{=}32$.}",
      r"\label{tab:adapt}", r"\footnotesize",
      r"\begin{tabular}{llcccc}", r"\toprule",
      r"Task & Metric & \#1 zero-shot & \#2 $N{=}32$ & $N{=}128$ & $N{=}512$ \\", r"\midrule"]
for tid, r in sorted(adapt["results"].items()):
    hf = r["head_fewshot"]
    cells = [hf.get(str(n), None) for n in (32, 128, 512)]
    t3.append(esc(tid) + f" & {r['metric']} & {r['zero_shot_1']:.3f} & " +
              " & ".join("--" if c is None else f"{c:.3f}" for c in cells) + r" \\")
t3 += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_3_adapt.tex").write_text("\n".join(t3))

# ---------------- Table 4: appendix per-seed per-family -------------------
seeds = ["20261001", "20261002", "20261003"]
def metric_of(prim, res):
    return {"choice": res.get("accuracy"), "noul": res.get("auroc"),
            "score": res.get("spearman"), "multi_noul": res.get("macro_f1")}[prim]

def per_family_agg(kind, seed):
    """kind: s1 -> per-family eval dirs; s2 -> whole-run eval_results.json"""
    acc = defaultdict(list)
    if kind == "s1":
        import glob
        for dd in sorted((AE).glob(f"s1_{seed}_*/eval_results.json")):
            for tid, r in load(dd)["results"].items():
                if "skip_reasons" in r and r.get("n", 0):
                    prim = r["primitive"]
                    m = metric_of(prim, r)
                    if m is not None:
                        acc[(family_of(tid), prim)].append(m)
    else:
        ev = load(TR / f"s2_{seed}" / "eval_results.json")["results"]
        for tid, r in ev.items():
            prim = r["primitive"]
            m = metric_of(prim, r)
            if m is not None:
                acc[(family_of(tid), prim)].append(m)
    return acc

combos = defaultdict(dict)   # (fam,prim) -> {seed: mean}
for seed in seeds:
    for kind in ("s1", "s2"):
        for key, ms in per_family_agg(kind, seed).items():
            combos[key].setdefault(kind, []).append(np.mean(ms))
t4 = [r"% Table 4: appendix per-family comparison (generated by gen_tables.py; seed-avg of per-task metrics)",
      r"\begin{table}[t]", r"\centering",
      r"\caption{Per-family, per-seed means for the two trained arms (task-macro of per-task seed means). "
      r"\#1 uses per-family early-stop checkpoints (37-task slice; families as in the training scheduler), "
      r"\#2 the full-run checkpoint. DeepLoc (multi\_noul) and double-sequence tasks are outside this harness.}",
      r"\label{tab:appendix}", r"\footnotesize",
      r"\begin{tabular}{llccc}", r"\toprule",
      r"Family & Primitive & \#1 (mean$\pm$std over 3 seeds) & \#2 & n \\ \midrule"]
for (f, p) in sorted(combos):
    a1 = np.array(combos[(f, p)].get("s1", []))
    a2 = np.array(combos[(f, p)].get("s2", []))
    if len(a1) == 0 and len(a2) == 0:
        continue
    s1 = f"{a1.mean():.3f}$\\pm${a1.std():.3f}" if len(a1) else "--"
    s2 = f"{a2.mean():.3f}$\\pm${a2.std():.3f}" if len(a2) else "--"
    n = max(len(a1), len(a2))
    t4.append(esc(f) + f" & {p} & {s1} & {s2} & {n} \\\\")
t4 += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_4_appendix.tex").write_text("\n".join(t4))

# ---------------- Table 5: phrasing x 3 checkpoints ------------------------
ab = load(AE / "noul_ablation_3seed.json")
PN = {"current_false_no": "false: no / true: yes", "plain_false_true": "false / true",
      "proposition": "proposition (``yes, it does'')", "raw_no_yes": "no / yes (trained)",
      "descriptive": "descriptive", "neg_pos_words": "neg / pos words"}
t5 = [r"% Table 5: noul phrasing x 3 stable checkpoints (gen_tables.py)",
      r"\begin{table}[t]", r"\centering",
      r"\caption{Noul AUROC on GB tasks for six candidate phrasings, evaluated on three "
      r"seed-averaged stable checkpoints (same weights per column; only rendered candidate "
      r"text varies). No phrasing reaches the per-task-head reference (0.629). "
      r"The trained phrasing is marked \dag.}",
      r"\label{tab:phrasing}", r"\small",
      r"\begin{tabular}{lcccc}", r"\toprule",
      r"Phrasing & s1 & s2 & s3 & mean$\pm$std \\ \midrule"]
for k, v in sorted(ab["per_phrasing"].items(), key=lambda kv: -kv[1]["mean"]):
    nm = PN[k] + (r"$^\dagger$" if k == ab["trained_phrasing"] else "")
    t5.append(nm + " & " + " & ".join(f"{x:.3f}" for x in v["per_seed"]) +
              f" & {v['mean']:.3f}$\\pm${v['std']:.3f} \\\\")
t5 += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_5_phrasing.tex").write_text("\n".join(t5))

# ---------------- Table 6: TAPE cross-family 3-seed ------------------------
tp = load(AE / "cross_family_tape_3seed.json")
t6 = [r"% Table 6: TAPE cross-family score arm, 3 seeds (gen_tables.py)",
      r"\begin{table}[t]", r"\centering",
      r"\caption{Cross-family score transfer (TAPE held out; DeepSTARR and ProteinGym score "
      r"families in training). Spearman per seed; ``abs'' = trained absolute value. "
      r"Stability's positive $\Delta$ reflects a pathological frozen baseline "
      r"($-0.218$) regressing toward zero, not genuine transfer.}",
      r"\label{tab:tape}", r"\small",
      r"\begin{tabular}{llccccc}", r"\toprule",
      r"Task & & frozen & tr.\ s1 & tr.\ s2 & tr.\ s3 & $\Delta$ mean$\pm$std \\ \midrule"]
for task, d in tp["per_task"].items():
    seeds = ["s1", "s2", "s3"]
    fr = np.mean([d["per_seed"][s]["frozen"] for s in seeds])
    trs = [d["per_seed"][s]["trained"] for s in seeds]
    t6.append(task.replace("_", "\\_") + r" & abs & " + f"{fr:.3f} & " +
              " & ".join(f"{x:.3f}" for x in trs) +
              f" & {d['mean_delta']:+.3f}$\\pm${d['std_delta']:.3f} \\\\")
t6 += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(FIG_DIR / "TABLE_6_tape.tex").write_text("\n".join(t6))
print("Wrote TABLE_1..6 tex. Table4 combos:", len(combos))
